### PR TITLE
Update tic-tac-toe to the latest version

### LINKED ISSUE #31: Examples not working
Hello,
when i try to open https://tic-tac-toe.meteorapp.com/
it says

> 503 Service Unavailable: No endpoints to handle the request. If you're the owner of this app, see this article for more information: http://bit.ly/2uCFzOo (7)

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Updated the tic-tac-toe example to the latest Meteor. Not sure who has originally deployed it as I was not able to do so in order to fix #31.

### CODE REVIEW

**Comment by Grubba27** [comment]
hello there. Made it work :) https://tic-tac-toe-example.meteorapp.com/

changed ``main.jsx`` file like this: 

```jsx
import React from 'react';
import { Meteor } from 'meteor/meteor';
import { App } from '/imports/ui/App';
import * as ReactDOM from "react-dom";

Meteor.startup(() => {

  const root = document.getElementById('react-target')
  ReactDOM.render(<App />, root)

});

```

also, on deploy, I used this command: `` meteor deploy tic-tac-toe-example.meteorapp.com --mongo`` so that meteor cloud could create a mongo DB for me

**Comment by StorytellerCZ** [comment]
@Grubba27 the question is who holds `tic-tac-toe.meteorapp.com`

**Comment by Grubba27** [comment]
Updated. Guess all works! Can I merge this PR or is there something left ?

**Comment by StorytellerCZ** [comment]
@Grubba27 ready to be merged

**Pull request merged**
