### PR TITLE
Add simple-photo and simple-map examples

### PR DESCRIPTION
**Pull request by StorytellerCZ**
From the meteor/mobile-packages repository.
https://github.com/meteor/mobile-packages

### CODE REVIEW

**Review by filipenevola — CHANGES_REQUESTED** [review]
Google Maps is not loading for me https://simple-map.meteorapp.com/

map 2021-10-05 10-33-21

**Comment by StorytellerCZ** [comment]
Yes, I send it in the other topic. The issue is that Google Maps is now payed or at least requires to have a payment account assigned to it. Do we want to do that or forgo Google?

**Review by kevin-tayong — APPROVED** [review]

**Comment by Grubba27** [comment]
Hey @StorytellerCZ, I guess we should forget google maps and them we are good to go :)

**Review by henriquealbert — APPROVED** [review]
You can remove google maps. The other map is working fine, @StorytellerCZ Thank you for your contribution 🙏🏻

**Comment by StorytellerCZ** [comment]
@henriquealbert I have submitted PR to mobile packages repository to update the examples there to Meteor 2.7.3: https://github.com/meteor/mobile-packages/pull/157

Once that is merged, you can merge this PR (which has been updated with the latest versions) as well.

**Comment by Grubba27** [comment]
> Once that is merged, you can merge this PR (which has been updated with the latest versions) as well.

- [x] Done

**Pull request merged**
